package database;

public enum DatabaseOperation {
	// update this accordingly
<<<<<<< HEAD
	INSERT, UPDATE, DELETE, ALTER, SELECT, DISPLAY, USER_LOGIN, FETCH_PRODUCTS_BY_CATEGORY, FETCH_ONLINE_ORDERS, UPDATE_ONLINE_ORDERS,ADD_PROMOTION, INSERT_PROMOTION_NAMES, SELECT_PROMOTIONS_TO_ACTIVE, UPDATE_PROMOTION_STATUS;
=======
	INSERT, UPDATE, DELETE, ALTER, SELECT_PROMOTION, DISPLAY, USER_LOGIN, FETCH_PRODUCTS_BY_CATEGORY, FETCH_ONLINE_ORDERS, UPDATE_ONLINE_ORDERS,ADD_PROMOTION, INSERT_PROMOTION_NAMES
	, SELECT, GENERIC_SELECT, FETCH_MACHINES_BY_LOCATION, FETCH_PRODUCTS_IN_MACHINE, UPDATE_PRODUCTS_IN_MACHINE; // my actual select -> I changed the old one to "select promotion" because it wasn't OK
>>>>>>> branch 'master' of https://github.com/rotemlv/FinalProjectEkt.git
}
