package Server;

public enum DatabaseOperation {
	// update this accordingly
	INSERT, UPDATE, DELETE, ALTER, SELECT, DISPLAY, USER_LOGIN, FETCH_PRODUCTS_BY_CATEGORY, FETCH_ONLINE_ORDERS, UPDATE_ONLINE_ORDERS;
}
